sudo: required
dist: trusty
language: node_js
node_js:
  - node

apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

cache:
  directories:
    - "node_modules"

before_script:
- npm install -g @angular/cli
- npm install -g karma
- npm install
- npm run build

script: karma start src/karma.conf.js --single-run

deploy:
  on:
      branch: master
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $AWS_BUCKET
  skip_cleanup: true
  local_dir: dist
  acl: public_read
  region: eu-west-3
